name: Basic workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Type checking and generate .d.ts files before packaging
        run: yarn tsc

      - name: Build all
        run: yarn build:all

      - name: Build image
        run: yarn workspace backend build-image

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test

  format:
    name: Formatting and type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fetch branch master
        run: git fetch origin master

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install

      - name: Prettier
        run: yarn prettier:check

      - name: Linting
        run: yarn lint
